### ISSUE TITLE
ERROR: Cannot uninstall 'wincertstore'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

### ISSUE THREAD

**Issue by human-ai2025** [full-stack-deep-learning/fsdl-text-recognizer-2021-labs#24]
**When I run make pip-tools, it seems that it doesn't work with pip sync giving an error like the below** 

> pip-sync requirements/prod.txt requirements/dev.txt
Found existing installation: wincertstore 0.2
ERROR: Cannot uninstall 'wincertstore'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ML_dev\envs\fsdl-text-recognizer-2021\Scripts\pip-sync.exe\__main__.py", line 7, in <module>
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\click\core.py", line 829, in __call__    return self.main(*args, **kwargs)
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\piptools\scripts\sync.py", line 151, in cli
    ask=ask,
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\site-packages\piptools\sync.py", line 227, in sync
    check=True,
  File "d:\ml_dev\envs\fsdl-text-recognizer-2021\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['d:\\ml_dev\\envs\\fsdl-text-recognizer-2021\\python.exe', '-m', 'pip', 'uninstall', '-y', 'wincertstore']' returned non-zero exit status 1.
make: *** [Makefile:14: pip-tools] Error 1`

operating system :- Windows 10 
Environment:- Anaconda 
GPU:- GTX 1650

**Comment by SasankYadati** [comment]
Adding wincerstore to dev requirements solved this for me. I don't foresee any issues due to this addition.
